# -*- coding: utf-8 -*-
"""latihan 8 praktikum analisis algoritma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jLCZZglOZTIR3VDotNPwa8RQuf3ueE9
"""

# Contoh Tanpa Memoization (Rekursif Fibonacci)

def fib_recursive(n):
    if n <= 1:
        return n
    return fib_recursive(n-1) + fib_recursive(n-2)

# Driver Program
n = 10
print("Fibonacci:", fib_recursive(n))

# Contoh Dengan Memoization
# Fibonacci Memoization
memo = {}

def fib_memo(n):
    if n in memo:
        return memo[n]

    if n <= 1:
        return n

    memo[n] = fib_memo(n-1) + fib_memo(n-2)
    return memo[n]

# Driver Program
n = 50
print("Fibonacci:", fib_memo(n))

# Contoh DP Bottom-Up Fibonacci

# Dynamic Programming Fibonacci
def fib_dp(n):
    if n <= 1:
        return n

    dp = [0] * (n + 1)

    dp[0] = 0
    dp[1] = 1

    for i in range(2, n + 1):
        dp[i] = dp[i-1] + dp[i-2]

    return dp[n]

# Driver Program
n = 50
print("Fibonacci DP:", fib_dp(n))

# Space Optimized DP Fibonacci
def fib_optimized(n):
    if n <= 1:
        return n

    a, b = 0, 1

    for _ in range(2, n + 1):
        a, b = b, a + b
    return b

# Driver Program
n = 50
print("Optimized Fibonacci:", fib_optimized(n))

# Greedy Coin Change
def coin_change_greedy (coins, amount):

    # Urutkan dari terbesar
    coins.sort(reverse=True)

    result = []

    for coin in coins:

        while amount >= coin:
            amount -= coin
            result.append(coin)

    return result

# Driver Program
coins = [100, 50, 25, 10, 5, 1]
amount = 289

hasil = coin_change_greedy (coins, amount)

print("Koin digunakan:", hasil)
print("Jumlah koin:", len(hasil))

# Coding DP Combination
def count_ways (coins, amount):
    dp = [0] * (amount + 1)
    dp[0] = 1
    for coin in coins:
        for i in range(coin, amount + 1):
            dp[i] += dp[i-coin]
    return dp[amount]

# Driver Program
coins = [1, 2, 5]
amount = 5

print("Jumlah kombinasi:", count_ways(coins, amount))