# -*- coding: utf-8 -*-
"""latihan 4 praktikum analisis algoritma_g211250086.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EGqrSaA5aFCK2CPAX9_8-E11bjvijxG4
"""

#Linear Search
def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1
# contoh
data = [10, 20, 30, 40, 50]
print(linear_search(data, 30)) # output: 2

# Binary Search (Iteratif)
def binary_search(arr, target):
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1
# contoh (data harus terurut)
data = [10, 20, 30, 40, 50]
print(binary_search(data, 40)) # output: 3

# Binary Search (Rekursif)
def binary_search_recursive(arr, left, right, target):
    if left > right:
        return -1
    mid = (left + right) // 2
    if arr[mid] == target:
        return mid
    elif arr[mid] < target:
        return binary_search_recursive(arr, mid + 1, right, target)
    else:
        return binary_search_recursive(arr, left, mid - 1, target)
# contoh
data = [10, 20, 30, 40, 50]
print(binary_search_recursive(data, 0, len(data)-1, 20)) # output: 1

# Jump Search
import math
def jump_search(arr, target):
    n = len(arr)
    step = int(math.sqrt(n))
    prev = 0
    # lompat blok
    while arr[min(step, n) - 1] < target:
        prev = step
        step += int(math.sqrt(n))
        if prev >= n:
            return -1
    # linear search di blok
    for i in range(prev, min(step, n)):
        if arr[i] == target:
            return i
    return -1
# contoh
data = [10, 20, 30, 40, 50, 60, 70]
print(jump_search(data, 60)) # output: 5

# Interpolation Search
def interpolation_search(arr, target):
    low = 0
    high = len(arr) - 1
    while low <= high and target >= arr[low] and target <= arr[high]:
        if low == high:
            if arr[low] == target:
                return low
            return -1
        # rumus interpolasi
        pos = low + ((target - arr[low]) * (high - low) //
                     (arr[high] - arr[low]))
        if arr[pos] == target:
            return pos
        elif arr[pos] < target:
            low = pos + 1
        else:
            high = pos - 1
    return -1
# contoh
data = [10, 20, 30, 40, 50]
print(interpolation_search(data, 50)) # output: 4