# -*- coding: utf-8 -*-
"""PRAKTIKUM 5 SORTING-G.211.25.0086.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vOECHm_oOC95ORIf3KDuosKaocmpQhz-
"""

def merge_sort(arr):                         # Fungsi utama Merge Sort
    if len(arr) > 1:                         # Jika array lebih dari 1 elemen → O(1)
        mid = len(arr) // 2                  # Membagi array → O(1)
        L = arr[:mid]                        # Membuat sub-array kiri → O(n)
        R = arr[mid:]                        # Membuat sub-array kanan → O(n)

        merge_sort(L)                        # Rekursi kiri → T(n/2)
        merge_sort(R)                        # Rekursi kanan → T(n/2)

        i = j = k = 0                        # Inisialisasi index → O(1)

        while i < len(L) and j < len(R):     # Loop penggabungan → O(n)
            if L[i] < R[j]:                  # Perbandingan → O(1)
                arr[k] = L[i]                # Assign → O(1)
                i += 1                       # Increment → O(1)
            else:
                arr[k] = R[j]                # Assign → O(1)
                j += 1                       # Increment → O(1)
            k += 1                           # Increment → O(1)

        while i < len(L):                    # Sisa elemen kiri → O(n)
            arr[k] = L[i]                    # Assign → O(1)
            i += 1                           # Increment → O(1)
            k += 1                           # Increment → O(1)

        while j < len(R):                    # Sisa elemen kanan → O(n)
            arr[k] = R[j]                    # Assign → O(1)
            j += 1                           # Increment → O(1)
            k += 1                           # Increment → O(1)

    return arr                               # Return hasil → O(1)


# contoh
data = [38, 27, 43, 3, 9, 82, 10]
print("Merge Sort:", merge_sort(data))