# -*- coding: utf-8 -*-
"""praktikum6_github_g211250086.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ivzj4vLfc_TFGmOcZIasClKPSoUwcacH
"""

import math

# -----------------------------
# 1. Hitung Mean tiap kolom
# -----------------------------
def hitung_mean(data):
    n = len(data)
    m = len(data[0])
    mean = [0] * m

    for j in range(m):
        total = 0
        for i in range(n):
            total += data[i][j]
        mean[j] = total / n

    return mean


# -----------------------------
# 2. Centering Data
# -----------------------------
def center_data(data, mean):
    centered = []
    for row in data:
        new_row = []
        for j in range(len(row)):
            new_row.append(row[j] - mean[j])
        centered.append(new_row)
    return centered


# -----------------------------
# 3. Covariance Matrix
# -----------------------------
def covariance_matrix(data):
    n = len(data)
    m = len(data[0])

    cov = [[0 for _ in range(m)] for _ in range(m)]

    for i in range(m):
        for j in range(m):
            total = 0
            for k in range(n):
                total += data[k][i] * data[k][j]
            cov[i][j] = total / (n - 1)

    return cov


# -----------------------------
# 4. Eigenvalue & Eigenvector (Power Iteration)
# -----------------------------
def dot(v1, v2):
    return sum(v1[i] * v2[i] for i in range(len(v1)))


def mat_vec_mul(matrix, vector):
    result = []
    for row in matrix:
        result.append(dot(row, vector))
    return result


def normalize(v):
    norm = math.sqrt(sum(x*x for x in v))
    return [x / norm for x in v]


def power_iteration(matrix, iterations=100):
    n = len(matrix)
    b_k = [1] * n  # vector awal

    for _ in range(iterations):
        b_k1 = mat_vec_mul(matrix, b_k)
        b_k = normalize(b_k1)

    # eigenvalue
    Av = mat_vec_mul(matrix, b_k)
    eigenvalue = dot(b_k, Av)

    return eigenvalue, b_k


# -----------------------------
# 5. PCA Function
# -----------------------------
def pca(data, k):
    # Step 1: Mean
    mean = hitung_mean(data)

    # Step 2: Centering
    centered = center_data(data, mean)

    # Step 3: Covariance Matrix
    cov = covariance_matrix(centered)

    # Step 4: Cari eigenvalue & eigenvector
    eigenvalues = []
    eigenvectors = []

    matrix_copy = [row[:] for row in cov]

    for _ in range(k):
        val, vec = power_iteration(matrix_copy)
        eigenvalues.append(val)
        eigenvectors.append(vec)

        # Deflation (menghilangkan komponen utama yang sudah diambil)
        for i in range(len(matrix_copy)):
            for j in range(len(matrix_copy)):
                matrix_copy[i][j] -= val * vec[i] * vec[j]

    # Step 5: Transform data
    transformed = []
    for row in centered:
        new_row = []
        for vec in eigenvectors:
            new_row.append(dot(row, vec))
        transformed.append(new_row)

    return transformed


# -----------------------------
# 6. Contoh Penggunaan
# -----------------------------
data = [
    [2.5, 2.4],
    [0.5, 0.7],
    [2.2, 2.9],
    [1.9, 2.2],
    [3.1, 3.0],
    [2.3, 2.7],
    [2.0, 1.6],
    [1.0, 1.1],
    [1.5, 1.6],
    [1.1, 0.9]
]

hasil = pca(data, k=1)

print("Hasil PCA (1 dimensi):")
for row in hasil:
    print(row)

import math

def euclidean_distance(x, y):
    # Pastikan dimensi sama
    if len(x) != len(y):
        return "Dimensi tidak sama"

    total = 0

    # Hitung jumlah kuadrat selisih
    for i in range(len(x)):
        selisih = x[i] - y[i]
        total += selisih * selisih

    # Akar kuadrat
    hasil = math.sqrt(total)

    return hasil


# -----------------------------
# Contoh penggunaan
# -----------------------------
titik1 = [2, 3]
titik2 = [5, 7]

jarak = euclidean_distance(titik1, titik2)
print("Jarak Euclidean:", jarak)