# -*- coding: utf-8 -*-
"""praktikum fungsi pca_g211250086.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fD2yTqZu6ajLOFLu8CdtaXwSxWY55vIT
"""

# Fungsi menghitung mean
def mean(data):
    return sum(data) / len(data)

# Transpose matrix
def transpose(matrix):
    return list(map(list, zip(*matrix)))

# Perkalian matrix
def multiply(A, B):
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

# Kurangi mean (normalisasi)
def normalize(X):
    means = [mean(col) for col in transpose(X)]
    norm = []
    for row in X:
        norm.append([row[i] - means[i] for i in range(len(row))])
    return norm

# Covariance matrix
def covariance(X):
    X_t = transpose(X)
    cov = []
    for i in range(len(X_t)):
        row = []
        for j in range(len(X_t)):
            val = 0
            for k in range(len(X)):
                val += X[k][i] * X[k][j]
            val /= (len(X) - 1)
            row.append(val)
        cov.append(row)
    return cov

# Power Iteration untuk cari eigen vector
def power_iteration(matrix, iterations=100):
    b = [1 for _ in range(len(matrix))]

    for _ in range(iterations):
        new_b = [0]*len(matrix)
        for i in range(len(matrix)):
            for j in range(len(matrix)):
                new_b[i] += matrix[i][j] * b[j]

        # normalisasi
        norm = sum(x*x for x in new_b) ** 0.5
        b = [x / norm for x in new_b]

    return b

# PCA utama
def pca(X, k):
    # Step 1: Normalisasi
    X_norm = normalize(X)

    # Step 2: Covariance
    cov = covariance(X_norm)

    # Step 3: Eigen vector (ambil satu saja sederhana)
    eigen_vectors = []
    for _ in range(k):
        vec = power_iteration(cov)
        eigen_vectors.append(vec)

    # Step 4: Proyeksi
    eigen_vectors_t = transpose(eigen_vectors)
    result = multiply(X_norm, eigen_vectors_t)

    return result


# =======================
# CONTOH DATA
X = [
    [2, 3],
    [3, 5],
    [4, 2],
    [5, 4]
]

hasil = pca(X, 1)

print("Hasil PCA:")
for row in hasil:
    print(row)